#1 
SELECT EMPLOYEES.LASTNAME,EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES,DEPARTMENTS 
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

#2
SELECT DISTINCT JOBS.JOB_ID, JOBS.JOB_TITLE,JOBS.MIN_SALARY,JOBS.MAX_SALARY, DEPARTMENTS.LOCATION_ID 
FROM DEPARTMENTS 
INNER JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID 
INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
WHERE DEPARTMENTS.DEPARTMENT_ID = 30;

#3
SELECT DISTINCT EMPLOYEES.LASTNAME, DEPARTMENTS.DEPARTMENT_NAME,LOCATIONS.LOCATION_ID,LOCATIONS.CITY 
FROM EMPLOYEES 
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.EMPLOYEE_ID 
INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID 
WHERE EMPLOYEES.COMMISSION_PCT IS NOT NULL;

#4
SELECT EMPLOYEES.LASTNAME, DEPARTMENTS.DEPARTMENT_NAME  
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
WHERE EMPLOYEES.LASTNAME LIKE "A%";

#5
SELECT EMPLOYEES.LASTNAME, JOBS.JOB_TITLE,DEPARTMENTS.DEPARTMENT_ID,DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES 
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID 
INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
WHERE LOCATIONS.CITY = "Toronto";

#6
SELECT EMPS.LASTNAME AS "employee",EMPS.EMPLOYEE_ID AS "emp#",MNG.LASTNAME AS "manager",MNG.EMPLOYEE_ID AS "manager#" 
FROM EMPLOYEES AS EMPS JOIN EMPLOYEES AS MNG ON EMPS.MANAGER_ID = MNG.EMPLOYEE_ID  

#12
SELECT MAX(SALARY) AS "MAXIMUM",MIN(SALARY) AS "MINIMUM",SUM(SALARY) AS "SUM",AVG(SALARY) AS "AVERAGE" 
FROM EMPLOYEES;

#13
SELECT JOBS.JOB_TITLE,MAX(SALARY) AS "MAXIMUM",MIN(SALARY) AS "MINIMUM",SUM(SALARY) AS "SUM",AVG(SALARY) AS "AVERAGE" 
FROM EMPLOYEES JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
GROUP BY EMPLOYEES.JOB_ID;

#14
SELECT JOBS.JOB_TITLE,COUNT(*) 
FROM EMPLOYEES JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
GROUP BY EMPLOYEES.JOB_ID;

#15
SELECT COUNT(DISTINCT MANAGER_ID) FROM EMPLOYEES;

#16
SELECT (MAX(SALARY)-MIN(SALARY)) AS "DIFFERENCE" FROM EMPLOYEES;

#17
SELECT MANAGER_ID, MIN(SALARY) AS MIN_SALARY 
FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT NULL AND SALARY >= 6000 
GROUP BY MANAGER_ID ORDER BY MIN_SALARY DESC;

#18

#19
SELECT LASTNAME,HIRE_DATE  FROM EMPLOYEES WHERE EMPLOYEES.LASTNAME = "Zlotkey";

#20
SELECT EMPLOYEE_ID,LASTNAME 
FROM EMPLOYEES 
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) 
ORDER BY SALARY;

#21

#22
SELECT EMPLOYEES.LASTNAME,EMPLOYEES.DEPARTMENT_ID,EMPLOYEES.JOB_ID 
FROM EMPLOYEES 
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID 
WHERE LOCATIONS.LOCATION_ID = 1700;

#23
SELECT E1.LASTNAME, E1.SALARY  FROM EMPLOYEES E1 JOIN EMPLOYEES E2 WHERE E1.MANAGER_ID =(SELECT E2.EMPLOYEE_ID WHERE E2.LASTNAME = "King");

#24
SELECT EMPLOYEE_ID,LASTNAME,JOB_ID  FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID WHERE EMPLOYEES.DEPARTMENT_ID = (SELECT DEPARTMENTS.DEPARTMENT_ID WHERE DEPARTMENT_NAME = "Executive");

#25

#26
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

#27
SELECT *  FROM EMPLOYEES ORDER BY FIRSTNAME DESC;

#28
SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS NAME, SALARY, ((15/100)*SALARY) AS PF  FROM EMPLOYEES;

#29
SELECT EMPLOYEE_ID, CONCAT(FIRSTNAME," ",LASTNAME) AS "NAME",SALARY  
FROM EMPLOYEES 
ORDER BY SALARY;

#30
SELECT DEPARTMENT_NAME,sum(SALARY) AS TOTAL_SALARY  
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
GROUP BY EMPLOYEES.DEPARTMENT_ID 
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;

#31
SELECT DEPARTMENT_NAME,min(SALARY) AS MIN_SALARY,max(SALARY) AS MAX_SALARY
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
GROUP BY EMPLOYEES.DEPARTMENT_ID 
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;

#32
SELECT DEPARTMENT_NAME,avg(SALARY) AS AVERAGE_SALARY,count(*) AS NUMBER_OF_EMPLOYEES
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
GROUP BY EMPLOYEES.DEPARTMENT_ID 
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;

#33
SELECT DISTINCT COUNT(*) AS "NUMBER OF EMPLOYEES" FROM EMPLOYEES;

#34
SELECT COUNT(DISTINCT JOB_ID) AS "NUMBER OF JOB_ID S" FROM EMPLOYEES;

#35
SELECT UPPER(FIRSTNAME) AS FIRST_NAME FROM EMPLOYEES;

#36
SELECT SUBSTRING(FIRSTNAME,1,3) AS NAME_ABBR FROM EMPLOYEES;

#37
SELECT CONCAT (FIRSTNAME," ",LASTNAME) AS NAME FROM EMPLOYEES;

#38
SELECT TRIM(FIRSTNAME) AS FIRST_NAME FROM EMPLOYEES;
#39
SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS NAME, LENGTH(CONCAT (TRIM(FIRSTNAME),TRIM(LASTNAME)))
AS LENGTH FROM EMPLOYEES;

#40
SELECT * FROM EMPLOYEES WHERE FIRSTNAME REGEXP '^[0-9]+$';

#41
SELECT * FROM EMPLOYEES LIMIT 10;

#42
SELECT LASTNAME, ROUND(SALARY,2) FROM EMPLOYEES;

#43
SELECT CONCAT(LASTNAME," ",FIRSTNAME) AS NAME,SALARY
FROM EMPLOYEES 
WHERE SALARY NOT BETWEEN 10000 AND 15000;

#44
SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS NAME,DEPARTMENT_ID 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 30 OR DEPARTMENT_ID =100;

#45
SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS NAME,SALARY  
FROM EMPLOYEES 
WHERE SALARY NOT BETWEEN 10000 AND 15000 AND DEPARTMENT_ID = 30 OR DEPARTMENT_ID =100;

#46
SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS NAME,HIRE_DATE 
FROM EMPLOYEES 
WHERE YEAR(HIRE_DATE) = 1987;

#47
SELECT FIRSTNAME FROM EMPLOYEES WHERE FIRSTNAME LIKE "%c%" AND FIRSTNAME LIKE "%b%";

#48
SELECT LASTNAME,JOBS.JOB_TITLE,SALARY 
FROM EMPLOYEES JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
WHERE (JOB_TITLE = "programmer" OR JOB_TITLE = "shipping clerk") AND (SALARY NOT IN
(4500,10000,15000)) ;

#49
SELECT LASTNAME FROM EMPLOYEES WHERE LENGTH(TRIM(LASTNAME)) = 6;

#50
SELECT LASTNAME FROM EMPLOYEES WHERE LASTNAME LIKE "__e%";

#51
#52
#53
#54
#55
#56
#57
#58
#59
#60
#61
#62
#63
#64
#65
#66
#67
#68
#69
#70
#71
#72
#73
#74
#75
#76
#77
#78
#79

#80
SELECT EMPLOYEES.EMPLOYEE_ID,EMPLOYEES.FIRSTNAME, EMPLOYEES.LASTNAME,DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES INNER JOIN DEPARTMENTS 
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

#81

#119
SELECT LASTNAME ,LEFT(REPLACE(PHONE_NUMBER,'.',''),4) AS "LAST FOUR DIGITS OF PH NO" 
FROM EMPLOYEES;



