SELECT EMPLOYEES.LASTNAME,EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES,DEPARTMENTS 
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT DISTINCT JOBS.JOB_ID, JOBS.JOB_TITLE,JOBS.MIN_SALARY,JOBS.MAX_SALARY, DEPARTMENTS.LOCATION_ID 
FROM DEPARTMENTS 
INNER JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID 
INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
WHERE DEPARTMENTS.DEPARTMENT_ID = 30;

SELECT DISTINCT EMPLOYEES.LASTNAME, DEPARTMENTS.DEPARTMENT_NAME,LOCATIONS.LOCATION_ID,LOCATIONS.CITY 
FROM EMPLOYEES 
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.EMPLOYEE_ID 
INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID 
WHERE EMPLOYEES.COMMISSION_PCT IS NOT NULL;

SELECT EMPLOYEES.LASTNAME, DEPARTMENTS.DEPARTMENT_NAME  
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
WHERE EMPLOYEES.LASTNAME LIKE "A%";

SELECT EMPLOYEES.LASTNAME, JOBS.JOB_TITLE,DEPARTMENTS.DEPARTMENT_ID,DEPARTMENTS.DEPARTMENT_NAME 
FROM EMPLOYEES 
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID 
INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
WHERE LOCATIONS.CITY = "Toronto";

SELECT EMPS.LASTNAME AS "employee",EMPS.EMPLOYEE_ID AS "emp#",MNG.LASTNAME AS "manager",MNG.EMPLOYEE_ID AS "manager#" 
FROM EMPLOYEES AS EMPS JOIN EMPLOYEES AS MNG ON EMPS.MANAGER_ID = MNG.EMPLOYEE_ID  

SELECT EMPS.LASTNAME AS "employee",EMPS.EMPLOYEE_ID AS "emp#",MNG.LASTNAME AS "manager",MNG.EMPLOYEE_ID AS "manager#" 
FROM EMPLOYEES AS EMPS JOIN EMPLOYEES AS MNG ON EMPS.MANAGER_ID = MNG.EMPLOYEE_ID  
ORDER BY EMPS.EMPLOYEE_ID;
#29
SELECT EMPLOYEE_ID, CONCAT(FIRSTNAME," ",LASTNAME) AS "NAME",SALARY  
FROM EMPLOYEES 
ORDER BY SALARY;

#30
SELECT DEPARTMENT_NAME,sum(SALARY) AS TOTAL_SALARY  
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
GROUP BY EMPLOYEES.DEPARTMENT_ID 
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;

#31
SELECT DEPARTMENT_NAME,min(SALARY) AS MIN_SALARY,max(SALARY) AS MAX_SALARY
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
GROUP BY EMPLOYEES.DEPARTMENT_ID 
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;

#32
SELECT DEPARTMENT_NAME,avg(SALARY) AS AVERAGE_SALARY,count(*) AS NUMBER_OF_EMPLOYEES
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
GROUP BY EMPLOYEES.DEPARTMENT_ID 
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;

#33
SELECT DISTINCT COUNT(*) AS "NUMBER OF EMPLOYEES" FROM EMPLOYEES;

#34
SELECT COUNT(DISTINCT JOB_ID) AS "NUMBER OF JOB_ID S" FROM EMPLOYEES;

#35
SELECT UPPER(FIRSTNAME) AS FIRST_NAME FROM EMPLOYEES;

#36
SELECT SUBSTRING(FIRSTNAME,1,3) AS NAME_ABBR FROM EMPLOYEES;

#37
SELECT CONCAT (FIRSTNAME," ",LASTNAME) AS NAME FROM EMPLOYEES;

#38
SELECT TRIM(FIRSTNAME) AS FIRST_NAME FROM EMPLOYEES;

#39
SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS NAME, LENGTH(CONCAT (TRIM(FIRSTNAME),TRIM(LASTNAME)))
AS LENGTH FROM EMPLOYEES;

#40


